# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        cct_db_provider:
            entity:
                class: AppBundle:User
                property: email

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_FOOD_CRUD
            - ROLE_FOOD_LIST
            - ROLE_FOODGROUP_CRUD
            - ROLE_MEAL_CRUD
            - ROLE_MEAL_LIST
            - ROLE_USER_CRUD
            - ROLE_USER_LIST
            - ROLE_UNITY_CRUD
            - ROLE_UNITY_LIST
        ROLE_FOOD_CRUD:
            - ROLE_FOOD_ADD
            - ROLE_FOOD_EDIT
            - ROLE_FOOD_DELETE
        ROLE_FOODGROUP_CRUD:
            - ROLE_FOODGROUP_ADD
            - ROLE_FOODGROUP_EDIT
            - ROLE_FOODGROUP_DELETE
        ROLE_MEAL_CRUD:
            - ROLE_MEAL_ADD
            - ROLE_MEAL_EDIT
            - ROLE_MEAL_DISABLE
        ROLE_USER_CRUD:
            - ROLE_USER_ADD
            - ROLE_USER_EDIT
            - ROLE_USER_DISABLE
        ROLE_UNITY_CRUD:
            - ROLE_UNITY_ADD
            - ROLE_UNITY_EDIT
            - ROLE_UNITY_DELETE

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   security_logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
