# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig.app_extension:
        public:    false
        class:     AppBundle\Twig\AppExtension
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@request_stack'
        tags:
            - { name: twig.extension }
